DoorsData = DoorsData or {}

DoorsData.WOW_TIPS = {
    "提示：钥石词缀会显著改变节奏，开打前先统一打断和减伤分工。",
    "提示：高层本里，灭团大多源于机制处理，不是单纯伤害不够。",
    "提示：合理留爆发给关键小怪波次，通常比全程无脑交技能更稳。",
    "提示：治疗留一个强力技能给意外情况，能大幅提高容错率。",
    "提示：多利用控制技能减少读条压力，队伍会更轻松。",
    "提示：开怪前标记目标并约定打断顺序，能减少很多失误。",
    "提示：移动中的小细节很重要，尽量边走位边保持输出循环。",
    "提示：了解每个本的高危技能，往往比盲目堆装等更有效。",
    "提示：拉怪节奏要和技能循环匹配，避免关键技能全在空档期。",
    "提示：遇到高压波次先保命再贪伤害，活着才有持续输出。",
    "提示：近战注意脚下与正面锥形，很多猝死都来自站位错误。",
    "提示：坦克开怪前说清路线，能有效减少误开和漏怪。",
    "提示：打断链断掉时，立刻补控而不是硬吃整条读条。",
    "提示：把位移技能留给机制处理，通常比当作纯加速更值。",
    "提示：治疗提前铺 HOT/护盾能显著降低爆发伤害窗口风险。",
    "提示：遇到长读条 boss 技能，先确认是否可规避再考虑硬抗。",
    "提示：团队减伤尽量轮转使用，不要全部堆在同一波。",
    "提示：熟悉每个职业的关键控制，副本容错会高很多。",
    "提示：仇恨不稳时先停手 1 秒，避免无意义减员。",
    "提示：清小怪时注意巡逻怪路径，避免连锁误拉。",
    "提示：钥石层数越高，路线和细节越重要，盲打很难稳定。",
    "提示：面对持续流血类伤害时，预留解控和驱散资源。",
    "提示：高层本中复活战术价值极高，别在低收益时机交掉。",
    "提示：能躲的技能就躲，治疗资源要留给不可避免伤害。",
    "提示：切目标前先看读条，优先处理危险施法单位。",
    "提示：副本里保持沟通简短明确，越关键时刻越需要清晰信息。",
    "提示：如果一波总是翻车，先复盘死因再调整拉法。",
    "提示：稳定通关来自一致执行，而不是偶尔的极限操作。",
}

-- 副本数据表：
-- name         英文名，主要给 tooltip 和后续 spell 名映射用。
-- subtitle     中文展示名。
-- spellID      对应传送法术 ID。
-- fallbackIcon 没有专用贴图时，先用一个图标做卡片主视觉。
-- color        每张卡片的主题色，用来区分 8 个副本。
DoorsData.DUNGEONS = {
    {
        name = "Cinderbrew Meadery",
        subtitle = "酒庄",
        spellID = 445440,
        fallbackIcon = 134758,
        seasons = { "11.0-S1", "11.1-S2", "11.2-S3" },
        color = {0.76, 0.45, 0.19},
    },
    {
        name = "Darkflame Cleft",
        subtitle = "暗焰裂口",
        spellID = 445441,
        fallbackIcon = 237555,
        seasons = { "11.0-S1", "11.1-S2", "11.2-S3" },
        color = {0.45, 0.23, 0.18},
    },
    {
        name = "Priory of the Sacred Flame",
        subtitle = "圣焰隐修院",
        spellID = 445444,
        fallbackIcon = 135805,
        seasons = { "11.0-S1", "11.1-S2", "11.2-S3" },
        color = {0.83, 0.48, 0.18},
    },
    {
        name = "The Rookery",
        subtitle = "驭雷栖巢",
        spellID = 445443,
        fallbackIcon = 132214,
        seasons = { "11.0-S1", "11.1-S2", "11.2-S3" },
        color = {0.48, 0.58, 0.77},
    },
    {
        name = "The Stonevault",
        subtitle = "矶石宝库",
        spellID = 1216786,
        fallbackIcon = 134449,
        seasons = { "11.0-S1", "11.2-S3" },
        color = {0.49, 0.46, 0.41},
    },
    {
        name = "The Dawnbreaker",
        subtitle = "破晨号",
        spellID = 445414,
        fallbackIcon = 136243,
        seasons = { "11.0-S1", "11.2-S3" },
        color = {0.89, 0.72, 0.36},
    },
    {
        name = "City of Threads",
        subtitle = "千丝之城",
        spellID = 1237215,
        fallbackIcon = 1386549,
        seasons = { "11.0-S1", "11.2-S3" },
        color = {0.53, 0.30, 0.47},
    },
    {
        name = "Ara-Kara, City of Echoes",
        subtitle = "回响之城",
        spellID = 445417,
        fallbackIcon = 5762016,
        seasons = { "11.0-S1", "11.2-S3" },
        color = {0.22, 0.52, 0.31},
    },
    {
        name = "Operation: Floodgate",
        subtitle = "洪水闸门行动",
        spellID = nil,
        fallbackIcon = 237275,
        seasons = { "11.1-S2" },
        color = {0.34, 0.59, 0.68},
    },
    {
        name = "The MOTHERLODE!!",
        subtitle = "暴富矿区",
        spellID = nil,
        fallbackIcon = 2065602,
        seasons = { "11.1-S2" },
        color = {0.75, 0.56, 0.20},
    },
    {
        name = "Theater of Pain",
        subtitle = "凋魂之殇剧场",
        spellID = nil,
        fallbackIcon = 3547168,
        seasons = { "11.1-S2" },
        color = {0.55, 0.25, 0.24},
    },
    {
        name = "Operation: Mechagon - Workshop",
        subtitle = "麦卡贡行动-车间",
        spellID = nil,
        fallbackIcon = 2915729,
        seasons = { "11.1-S2" },
        color = {0.42, 0.66, 0.63},
    },
    {
        name = "Eco-Dome Al'dani",
        subtitle = "生态圆顶",
        spellID = nil,
        fallbackIcon = 6257372,
        seasons = { "11.2-S3", "12.0-S1" },
        color = {0.26, 0.67, 0.46},
    },
}
